// <auto-generated />
using System;
using CrackTheCode.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrackTheCode.Infrastructure.Migrations
{
    [DbContext(typeof(CrackTheCodeDbContext))]
    [Migration("20260622150000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CrackTheCode.Domain.Entities.Clue", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Guess").HasColumnType("TEXT");
                    b.Property<Guid>("PuzzleId").HasColumnType("TEXT");
                    b.Property<int?>("SecondaryValue").HasColumnType("INTEGER");
                    b.Property<int>("Type").HasColumnType("INTEGER");
                    b.Property<int>("Value").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("PuzzleId");
                    b.ToTable("Clues");
                });

            modelBuilder.Entity("CrackTheCode.Domain.Entities.DailyPuzzle", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("Date").HasColumnType("TEXT");
                    b.Property<string>("PuzzleJson").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Seed").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("Date").IsUnique();
                    b.ToTable("DailyPuzzles");
                });

            modelBuilder.Entity("CrackTheCode.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<int>("Difficulty").HasColumnType("INTEGER");
                    b.Property<int>("DigitsCount").HasColumnType("INTEGER");
                    b.Property<int>("ElapsedSeconds").HasColumnType("INTEGER");
                    b.Property<DateTime?>("EndTime").HasColumnType("TEXT");
                    b.Property<int>("GuessesCount").HasColumnType("INTEGER");
                    b.Property<bool>("IsCompleted").HasColumnType("INTEGER");
                    b.Property<bool>("IsWon").HasColumnType("INTEGER");
                    b.Property<int>("Mode").HasColumnType("INTEGER");
                    b.Property<Guid>("PuzzleId").HasColumnType("TEXT");
                    b.Property<string>("PuzzleSecretCode").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("StartTime").HasColumnType("TEXT");
                    b.Property<int>("TimeLimitSeconds").HasColumnType("INTEGER");
                    b.Property<Guid?>("UserId").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("CrackTheCode.Domain.Entities.Puzzle", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<bool>("AllowDuplicates").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("Difficulty").HasColumnType("INTEGER");
                    b.Property<int>("DigitsCount").HasColumnType("INTEGER");
                    b.Property<int>("MaxDigit").HasColumnType("INTEGER");
                    b.Property<int>("MinDigit").HasColumnType("INTEGER");
                    b.Property<string>("SecretCode").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("CrackTheCode.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Username").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("CrackTheCode.Domain.Entities.Clue", b =>
                {
                    b.HasOne("CrackTheCode.Domain.Entities.Puzzle", "Puzzle")
                        .WithMany("Clues")
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Puzzle");
                });

            modelBuilder.Entity("CrackTheCode.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("CrackTheCode.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("User");
                });

            modelBuilder.Entity("CrackTheCode.Domain.Entities.Puzzle", b =>
                {
                    b.Navigation("Clues");
                });
        }
    }
}
